import { StyleSheet } from 'react-native';
export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#F8FAFC',
    },
    header: {
        paddingHorizontal: 16,
        paddingVertical: 16,
        paddingTop: 24,
        backgroundColor: '#FFFFFF',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        borderBottomWidth: 1,
        borderBottomColor: '#E2E8F0',
    },
    headerTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: '#1E293B',
    },
    progressContainer: {
        paddingHorizontal: 16,
        paddingVertical: 12,
        backgroundColor: '#FFFFFF',
        borderBottomWidth: 1,
        borderBottomColor: '#E2E8F0',
    },
    progressText: {
        fontSize: 12,
        color: '#64748B',
        fontWeight: '500',
        marginBottom: 8,
    },
    progressBar: {
        width: '100%',
        height: 6,
        backgroundColor: '#E2E8F0',
        borderRadius: 3,
        overflow: 'hidden',
    },
    progressFill: {
        width: '75%',
        height: '100%',
        backgroundColor: '#2563EB',
    },
    mapContainer: {
        flex: 1,
        backgroundColor: '#E2E8F0',
        position: 'relative',
    },
    map: {
        flex: 1,
    },
    mapPlaceholder: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    mapPlaceholderText: {
        fontSize: 14,
        color: '#64748B',
    },
    compassButton: {
        position: 'absolute',
        bottom: 80,
        right: 16,
        width: 50,
        height: 50,
        borderRadius: 25,
        backgroundColor: '#FFFFFF',
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 4,
    },
    bottomCard: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        backgroundColor: '#FFFFFF',
        paddingHorizontal: 16,
        paddingVertical: 20,
        borderTopLeftRadius: 20,
        borderTopRightRadius: 20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: -4 },
        shadowOpacity: 0.1,
        shadowRadius: 8,
        elevation: 8,
    },
    confirmationHeader: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        marginBottom: 16,
    },
    confirmationIcon: {
        marginRight: 12,
        marginTop: 4,
    },
    confirmationContent: {
        flex: 1,
    },
    confirmationTitle: {
        fontSize: 14,
        fontWeight: '600',
        color: '#16A34A',
        marginBottom: 4,
    },
    addressText: {
        fontSize: 14,
        fontWeight: '600',
        color: '#1E293B',
        marginBottom: 4,
    },
    coordsText: {
        fontSize: 11,
        color: '#64748B',
    },
    infoBox: {
        paddingVertical: 10,
        paddingHorizontal: 12,
        backgroundColor: '#DBEAFE',
        borderRadius: 8,
        marginBottom: 16,
        borderLeftWidth: 4,
        borderLeftColor: '#0284C7',
    },
    infoText: {
        fontSize: 12,
        color: '#0C4A6E',
        lineHeight: 16,
    },
    continueButton: {
        paddingVertical: 16,
        paddingHorizontal: 16,
        backgroundColor: '#22C55E',
        borderRadius: 12,
        alignItems: 'center',
        marginBottom: 16,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 4,
    },
    continueButtonText: {
        fontSize: 16,
        fontWeight: '700',
        color: '#FFFFFF',
    },
    adjustButton: {
        paddingVertical: 12,
        paddingHorizontal: 16,
        borderWidth: 1,
        borderColor: '#2563EB',
        borderRadius: 8,
        alignItems: 'center',
    },
    adjustButtonText: {
        fontSize: 14,
        fontWeight: '600',
        color: '#2563EB',
    },
});
