import { StyleSheet } from 'react-native';
export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#F8FAFC',
    },
    header: {
        paddingHorizontal: 16,
        paddingVertical: 16,
        paddingTop: 24,
        backgroundColor: '#FFFFFF',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        borderBottomWidth: 1,
        borderBottomColor: '#E2E8F0',
    },
    headerTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: '#1E293B',
    },
    progressContainer: {
        paddingHorizontal: 16,
        paddingVertical: 12,
        backgroundColor: '#FFFFFF',
        borderBottomWidth: 1,
        borderBottomColor: '#E2E8F0',
    },
    progressText: {
        fontSize: 12,
        color: '#64748B',
        fontWeight: '500',
        marginBottom: 8,
    },
    progressBar: {
        width: '100%',
        height: 6,
        backgroundColor: '#E2E8F0',
        borderRadius: 3,
        overflow: 'hidden',
    },
    progressFill: {
        width: '25%',
        height: '100%',
        backgroundColor: '#2563EB',
    },
    scrollContent: {
        flexGrow: 1,
        paddingHorizontal: 16,
        paddingVertical: 20,
    },
    alertBox: {
        paddingVertical: 14,
        paddingHorizontal: 14,
        backgroundColor: '#FEF3C7',
        borderRadius: 12,
        borderLeftWidth: 4,
        borderLeftColor: '#F59E0B',
        marginBottom: 20,
    },
    alertTitle: {
        fontSize: 15,
        fontWeight: '700',
        color: '#B45309',
        marginBottom: 6,
    },
    alertText: {
        fontSize: 13,
        color: '#92400E',
        lineHeight: 20,
    },
    cameraButton: {
        paddingVertical: 48,
        paddingHorizontal: 16,
        backgroundColor: '#FFFFFF',
        borderRadius: 16,
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 28,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 4,
    },
    cameraIconContainer: {
        width: 90,
        height: 90,
        borderRadius: 45,
        backgroundColor: '#EFF6FF',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 16,
    },
    cameraButtonTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: '#1E293B',
        marginBottom: 8,
    },
    cameraButtonSubtitle: {
        fontSize: 14,
        color: '#64748B',
    },
    tipsSection: {
        marginBottom: 20,
    },
    tipsTitle: {
        fontSize: 14,
        fontWeight: '600',
        color: '#1E293B',
        marginBottom: 12,
    },
    tipItem: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        marginBottom: 10,
    },
    tipCheck: {
        width: 20,
        height: 20,
        borderRadius: 10,
        backgroundColor: '#DCFCE7',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 10,
        marginTop: 2,
    },
    tipCheckText: {
        color: '#16A34A',
        fontWeight: '600',
        fontSize: 12,
    },
    tipText: {
        fontSize: 13,
        color: '#475569',
        flex: 1,
        lineHeight: 18,
    },
    infoBox: {
        paddingVertical: 12,
        paddingHorizontal: 12,
        backgroundColor: '#DBEAFE',
        borderRadius: 12,
        borderLeftWidth: 4,
        borderLeftColor: '#0284C7',
    },
    infoText: {
        fontSize: 13,
        color: '#0C4A6E',
        lineHeight: 18,
    },
});
